# Generated by Django 5.2.3 on 2025-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('servicio', models.CharField(choices=[('siesa', 'Siesa – POS PVD'), ('didi', 'Didi Food – Canales Digitales'), ('planta', 'Planta – Call Center')], max_length=50)),
                ('latencia', models.FloatField()),
                ('packet_loss', models.FloatField()),
                ('jitter', models.FloatField()),
                ('link', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
